### ISSUE TITLE
Exception when running single realization with MIN_REALIZATIONS defined in config

### ISSUE THREAD

**Issue by ManInFez** [Statoil/ert#203]
https://github.com/Statoil/ert/blob/1f304612b3a5071aff974529340aabe07c80bdb3/python/python/ert_gui/simulation/models/base_run_model.py#L219-L224

This function raises exception when running single realization test run. When it is fetching ensemble size it gets the number realizations defined in config when it should be one.

**Comment by markusdregi** [comment]
Well spotted! Luckily the single realization test run is for debugging to begin with, so it will. It his our users very hard 👍 Should however be fixed and my initial guess is that the single realization test run should edit the configuration in some way. Or, overload the validation method. The later might be much easier..

**Comment by stefoss23** [comment]
The idea behind the single-realization test run was to provoke errors early on for a certain config setup. If user started the real simulation, using several machines and the simulation failed due to a faulty setup or code error, it would be a huge waste of resources. A user can run the single-realization before doing large resource-demanding simulations. It really shouldn't be necessary to rewrite any config file for the single-realization to run. However, there is now a bug related to this specific code.
